### ISSUE TITLE
Support for statically position next/previous buttons

### ISSUE THREAD

**Issue by dtmnash** [jwarby/jquery-pagewalkthrough#67]
Great Plugin! we would love to see support for statically positioned next/previous buttons.

**Comment by jwarby** [comment]
Hi @dtmnash, this should be achievable with CSS (`position: fixed`), but will require a small change to the JS code first - we will need to append the buttons to a different element (specifically: `#jpwTooltip`, before `#bottom-scratch`, instead of `#tooltipWrapper`).

If you think this will be sufficient for your needs, then I'll try and get around to implementing that at the weekend.

**Comment by dtmnash** [comment]
@jwarby i think that sounds like it would work well. also need to think about what to do if the element the buttons are fixed to is on top of the element that is being highlighted. 

Would #bottom-scratch fix them to the bottom of the screen?

**Comment by jwarby** [comment]
`#bottom-scratch` is the element highlighted here:

![jquery page walkthrough by warby-](https://cloud.githubusercontent.com/assets/617098/11107951/6fb2b8c4-891d-11e5-87d3-33efdc8a661b.jpg)

It won't fix the buttons to the bottom or anything - the buttons just need to be adjacent to `#bottom-scratch` so that CSS `position: fixed` can be used to place them anywhere on the screen.  As it stands, using `position: fixed` will constrain the buttons to the text's container element (there are ways around it but they wouldn't be pretty, e.g. `left: -500px` or something):

![screenshot from 2015-11-12 09-14-38 png](https://cloud.githubusercontent.com/assets/617098/11107995/f4a8767c-891d-11e5-96d9-1bde420106f9.jpg)

**Comment by dtmnash** [comment]
thank you for the explanation. we were hoping to be able to fix them to the page outside of the tooltip so that the user can easily keep the mouse in one position and click through the different tooltips

**Comment by jwarby** [comment]
@dtmnash Sounds cool, should be easily achievable with the proposed changes! :+1:

**Comment by jwarby** [comment]
Hey @dtmnash, sorry I haven't had time to do this yet - should be able to look for you this weekend though.  My apologies.
