### ISSUE TITLE
lockScrolling option not working?

### ISSUE THREAD

**Issue by piotrkulpinski** [jwarby/jquery-pagewalkthrough#70]
Hi guys, 
I'm having trouble setting lockScrolling option to work. It's set for the current step and I can still scroll the content beneath the walkthrough.
Could you please check if this option is working in the most recent version?

Thanks

**Comment by piotrkulpinski** [comment]
I can only see it in the list of option in the code so that's why it's not working. Do you plan to implement it in near future? If not maybe it's a good idea to remove it from the list as it's confusing right now.

**Comment by jwarby** [comment]
Hi @piotrkulpinski, sorry for the confusion. I've not had a look through the logs yet to see what happened with that, but we probably won't end (re?)implementing it.

It should be easy enough to add scroll restrictions in the start/end callbacks for your walkthroughs though (which is why we probably won't end up putting into the plugin's code).

Apologies again, will remove the option from the list this coming week.
